projects:
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      endpoints:
        default: "http://localhost:4466/diarum/dev"

  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000